application: smaldonadoespinosa
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: .*
  script: index.html

  
- url: /css
  static_dir: css
- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /font
  static_dir: font

- url: /documents
  static_dir: documents




